# Generated by Django 4.0.2 on 2022-02-15 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('role', models.CharField(blank=True, max_length=255, null=True, verbose_name='Role')),
                ('permissions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Permissions')),
                ('permission_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Code')),
                ('permission_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name')),
                ('group', models.CharField(blank=True, max_length=255, null=True, verbose_name='Group')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='contenttypes.contenttype')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('project_name', models.CharField(max_length=255, verbose_name='Project Name')),
                ('project_type', models.CharField(blank=True, choices=[('EC', 'Ecommerce'), ('AL', 'Analytics'), ('BL', 'Blog'), ('IM', 'Image Gallery'), ('PR', 'Personal')], max_length=2, null=True, verbose_name='Project Type')),
                ('project_desc', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('is_expired', models.BooleanField(blank=True, null=True, verbose_name='Expired')),
                ('download_count', models.IntegerField(blank=True, null=True, verbose_name='Download Count')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
    ]
